GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

PUT http://localhost:3001/api/persons/62e97bebba50a0a3856f9dec
Content-Type: application/json

{
    "name": "dasdasd",
    "number": ""
}

###

GET http://localhost:3001/api/persons/62e96fe136254b827a0

###

DELETE http://localhost:3001/api/persons/4

###

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "",
    "number": "39-23-6423122"
}